name: replace-str
author: gendloop
description: 'Replace string in file'
inputs:
# Required
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}
  path-to-replace:
    description: 'File path to replace'
    required: true
    default: ""
  replace-to-path:
    description: 'Replace to file path'
    required: true
    default: ""
  str-to-replace:
    description: 'String to replace'
    required: true
    default: ""
  replace-to-str:
    description: 'Replace to string'
    required: true
    default: ""

runs:
  using: 'composite'
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3
      with: 
        token: ${{ inputs.token }}

    - name: git-pull
      shell: bash
      run: |
        git pull

    - name: replace-str
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
          GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        ls ${{ github.action_path }}/docs
        perl "${{ github.action_path }}/docs/replace.pl" "${{ inputs.path-to-replace }}" "${{ inputs.replace-to-path }}" "${{ inputs.str-to-replace }}" "${{ inputs.replace-to-str }}"

    - name: git-push
      uses: gendloop/git-push@main
      with:
        token: ${{ github.token }}
        commit: "chore: replace \\`${{ inputs.str-to-replace }}\\` in \\`${{ inputs.path-to-replace }}\\` to \\`${{ inputs.replace-to-str }}\\` in \\`${{ inputs.replace-to-path }}\\` "